{% set name = "py-exe-builder" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py-exe-builder-{{ version }}.tar.gz
  sha256: 9bb355b1bf288250028387f778e1d3508917c410b0501ff5dc422e3c1f174059

build:
  script: {{ PYTHON }} -m pip install . -vv
  #Not yet ready for Python 3.11
  number: 10
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - py2exe <0.13
    #Relies on build_exe command line interface which is removed at 0.13.0 
    - python >={{ python_min }},<3.12
    - __win   # [win]

test:
  imports:
    - pyexebuilder
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/j5int/py-exe-builder
  summary: Uses py2exe to create small exe stubs that leverage a full python installation, rather than packing the required pyc files in to the executable.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/j5int/py-exe-builder

extra:
  recipe-maintainers:
    - HeavyTony2
